[tox]
envlist =
    py3{12,13,14}{,-oldestdeps,-cov}
    lint
    docs
requires =
    tox-uv
isolated_build = true

[gh]
python =
    3.12 = py312
    3.13 = py313
    3.14 = py314, lint, docs

# Run the main test suite
[testenv]
set_env =

    # Set platform
    PLATFORM = unknown
    linux: PLATFORM = linux
    darwin: PLATFORM = mac
    win32: PLATFORM = windows

allowlist_externals =
    echo
description =
    run tests
    oldestdeps: with the oldest supported dependencies
    cov: with coverage
deps =
    oldestdeps: minimum_dependencies
extras =
    test
commands =

    echo Running on {env:PLATFORM}

    {list_dependencies_command}

    # Run tests
    pytest \
    cov: --cov --cov-branch --cov-report=xml:{env:PLATFORM}-{envname}-coverage.xml \
    cov: --junitxml={env:PLATFORM}-{envname}-junit.xml -o junit_family=legacy \
    {posargs}

# Run lint
[testenv:lint]
description = run linters
extras =
    test-ruff
commands = ruff check {posargs}

# Build documentation
[testenv:docs]
changedir =
    docs
description =
    invoke sphinx-build to build docs, check links, report coverage
extras =
    docs
commands =
    echo Building docs
    sphinx-build -W -b html . _build/html {posargs}
    echo Checking links
    sphinx-build -W -b linkcheck . _build/linkcheck {posargs}
    echo Checking coverage
    sphinx-build -W -b coverage . _build/coverage {posargs}
